default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: class_production_development

test:
  <<: *default
  database: class_production_test

production:
  <<: *default
  database: class_production_production
  username: class_production
  password: <%= ENV['CLASS_PRODUCTION_DATABASE_PASSWORD'] %>